### ISSUE TITLE
Remove trailing whitespace

### ISSUE THREAD

**Issue by SimonN** [kieranmillar/lem3edit#1]
I suggest that the codebase adhere to the following conventions:
* Remove trailing whitespace: There are no spaces/tabs immediately before a linebreak.
* The final line of each file is terminated with a linebreak.

Creating commits against a codebase that has trailing whitespace needs extra attention or tricky git configuration. Seemingly-harmless changes could result in merge conflics. Can you configure your editor or IDE to prune trailing whitespace automatically on saving?

(It's not important whether the linebreak is LF, CR, or CRLF, as long as the same linebreak is used consistently. It's also not important whether indentations are tabs or spaces, because editors should recognize that automatically.)

**Comment by kieranmillar** [comment]
A good idea. I have gone with both of these suggestions and added an extension to do these automatically.
